remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Borealis (Dataverse) API Demos
description: "Examples and code for using Github Pages with Dataverse"
show_downloads: "true"
