remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Borealis (Dataverse) + Github Pages Demos
description: "Examples and code for using Github Pages with the Dataverse API"
show_downloads: "true"
